class AvailableMeetingsStatesEmployee{}
class AvailableMeetingLoadingState extends AvailableMeetingsStatesEmployee{}
class AvailableMeetingSuccessState extends AvailableMeetingsStatesEmployee{}
class AvailableMeetingErrorState extends AvailableMeetingsStatesEmployee{}
