
class MyScheduleMeetings{}
class GetNotConfirmedMeetingsLoadingState extends MyScheduleMeetings{}
class GetNotConfirmedMeetingsSuccussState extends MyScheduleMeetings{}
class GetNotConfirmedMeetingsErrorState extends MyScheduleMeetings{}