class AcceptMeetingTimeCubitStates{}
class AcceptMeetingTimeIdlestate extends AcceptMeetingTimeCubitStates{}

class AcceptMeetingTimeLoadingstate extends AcceptMeetingTimeCubitStates{}
class AcceptMeetingTimeSucssesstate extends AcceptMeetingTimeCubitStates{}
class AcceptMeetingTimeErrorstate extends AcceptMeetingTimeCubitStates{}
